version: "3.8"

services:
  django:
    build: .
    container_name: djangodo
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A todo_project worker -l info
    volumes:
      - .:/app
    depends_on:
      - django
      - redis
  redis:
    image: redis:alpine
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    container_name: redis
